index:index.cpp
	@g++ index.cpp -o index

test:
	@./index $(n)
	
	@echo -e "**** index.txt ****"
	@cat index.txt

	@echo -e "\n\n**** dict.txt ****"
	@cat dict.txt

	@echo -e  "\n\n**** list.txt ****"
	@cat list.txt

clean:
	@rm -rf index index.txt dict.txt list.txt
