.TH CREPLAY 1 "Feb 10, 1992" "Creplay"

.SH NAME
creplay -- execute commands from an untrace


.SH SYNOPSIS
 

.nf

creplay file

.fi 

.PP

.SH DESCRIPTION
 
creplay executes the commands in \fIfile\fR produced by untrace.  If
the command file is a skeleton file, it will create a file system
skeleton under the name ``root'' in the current directory.  For a
replay file, the action will happen under ``root'' in that directory.

.PP

.SH OPTIONS

.PD 0
 
.TP 12

.BR -g
 Use if file system does not support chown of group ID.

.TP

.BR -v
 Verbose mode.


.PP

.SH DIAGNOSTICS

If any of the commands in \fIfile\fR does not complete successfully,
creplay dies with an assertion failure.  Any error will do, so make
sure you have the appropriate permissions to write into the current
directory, and make sure you have enough space for a (potentially)
large tree.

.PP

.SH AUTHOR
 
James J.  Kistler
